__description__ = "Devo Python Library."
__url__ = "http://www.devo.com"
__version__ = "5.1.8"
__author__ = "Devo"
__author_email__ = "support@devo.com"
__license__ = "MIT"
__copyright__ = "Copyright 2023 Devo"
